
-- h2 Database

-- optional: required only when USER_SCHEMA2 reference is declared;
CREATE SCHEMA USER_SCHEMA2 AUTHORIZATION SA;



DROP TABLE IF EXISTS USER_SCHEMA2.USER_ENTITY;

create table USER_SCHEMA2.USER_ENTITY (
   ID_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME_USER varchar(100) NOT NULL,
   PASSWORD_USER varchar(100) NOT NULL,
   EMAIL_USER varchar(100) NOT NULL,
   TYPE_GENDER_USER int DEFAULT 1,
   AGREEMENT_USER BOOL DEFAULT FALSE
);



DROP TABLE IF EXISTS USER_SCHEMA2.EMPLOYEE_ENTITY;

create table USER_SCHEMA2.EMPLOYEE_ENTITY (
   ID_EMP BIGINT AUTO_INCREMENT PRIMARY KEY,
   ID_USER BIGINT,
   FNAME_EMP varchar(100) NOT NULL,
   LNAME_EMP varchar(100),
   CH_NAME_EMP varchar(100) NOT NULL,
   COVID19_STATUS_EMP BOOL DEFAULT TRUE,
   EMAIL_EMP varchar(100),
   TYPE_GENDER_EMP int DEFAULT 1,
   STATUS_MARITAL_EMP char(10) DEFAULT 'SINGLE',
   TYPE_PREF_CONTACT_EMP char(2) DEFAULT 'EM',
   BODY_TYPE_EMP char(10) DEFAULT 'AVERAGE',
   DISABILITY_EMP char(1) DEFAULT 1,
   WALLET_BALANCE_EMP NUMBER(10,2) DEFAULT NULL,
   AGE_EMP NUMBER(2),
   DOB_EMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   
   FOREIGN KEY (ID_USER) REFERENCES USER_ENTITY (ID_USER),
   CONSTRAINT marcons CHECK (STATUS_MARITAL_EMP IN ('SINGLE', 'MARRIED', 'DIVORCED')),
   CONSTRAINT cpcons CHECK (TYPE_PREF_CONTACT_EMP IN ('MO', 'OF', 'HO', 'ME', 'EM')),
   CONSTRAINT btcons CHECK (BODY_TYPE_EMP IN ('AVERAGE', 'SLIM', 'HEAVY')),
   CONSTRAINT dobcons CHECK (DOB_EMP <= CURRENT_TIMESTAMP),
   CONSTRAINT chncons CHECK (CH_NAME_EMP like 'CH%')
);

COMMENT ON COLUMN USER_SCHEMA2.EMPLOYEE_ENTITY.TYPE_PREF_CONTACT_EMP IS 'Preferred way to contact with employee';


-- drop table USER_SCHEMA2.EMPLOYEE_ENTITY;
-- select * from USER_SCHEMA2.EMPLOYEE_ENTITY;


