
-- h2 Database


DROP TABLE IF EXISTS EMPLOYEE_ENTITY;

create table EMPLOYEE_ENTITY (
   ID_EMP BIGINT AUTO_INCREMENT PRIMARY KEY,
   FNAME_EMP varchar(100) NOT NULL,
   LNAME_EMP varchar(100),
   CH_NAME_EMP varchar(100) NOT NULL,
   COVID19_STATUS_EMP BOOL DEFAULT TRUE,
   EMAIL_EMP varchar(100),
   TYPE_GENDER_EMP char(1) DEFAULT 1,
   STATUS_MARITAL_EMP char(10) DEFAULT 'SINGLE',
   TYPE_PREF_CONTACT_EMP char(2) DEFAULT 'EM',
   WALLET_BALANCE_EMP NUMBER(10,2) DEFAULT NULL,
   AGE_EMP NUMBER(2),
   DOB_EMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   
   CONSTRAINT marcons CHECK(STATUS_MARITAL_EMP IN ('SINGLE', 'MARRIED', 'DIVORCED')),
   CONSTRAINT cpcons CHECK(TYPE_PREF_CONTACT_EMP IN ('MO', 'OF', 'HO', 'ME', 'EM')),
   CONSTRAINT dobcons CHECK(DOB_EMP <= CURRENT_TIMESTAMP),
   CONSTRAINT chncons CHECK(CH_NAME_EMP like 'CH%')
);

COMMENT ON COLUMN EMPLOYEE_ENTITY.TYPE_PREF_CONTACT_EMP IS 'Preferred way to contact with employee';


-- drop table EMPLOYEE_ENTITY;
-- select * from EMPLOYEE_ENTITY;


